name: All up test

on:
  push:
    branches: [master, althea-peggy]
  pull_request:
    branches: [master, althea-peggy]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run all up test in docker container
        run: bash tests/all-up-test.sh
